[theme]
primaryColor = "#ff6b35"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200

[runner]
magicEnabled = false

[client]
showErrorDetails = true